# syntax=docker/dockerfile:1


FROM node:latest
RUN mkdir -p /app

# Set /app as the working directory
WORKDIR /app

# Copy package.json and package-lock.json
# to the /app working directory
COPY . /app

# Install dependencies in /app
RUN npm install
# copy rest files into / app
COPY . /app
EXPOSE 3001
CMD ["npm", "start"]
