# syntax=docker/dockerfile:1


FROM node:latest

# Set /app as the working directory
WORKDIR /.

# Copy package.json and package-lock.json
# to the /app working directory
COPY . .

# Install dependencies in /app
RUN npm install
# copy rest files into / app
EXPOSE 3001
CMD ["npm", "start"]
